services:
  - type: web
    name: alx-backend-security
    runtime: python
    region: oregon
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn alx_backend_security.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: 'False'
